/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Apps */
        get: operations["list_apps_api_apps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feedback */
        get: operations["list_feedback_api_feedback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/{feedback_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feedback */
        get: operations["get_feedback_api_feedback__feedback_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drafts */
        get: operations["list_drafts_api_drafts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/drafts/{draft_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Draft */
        get: operations["get_draft_api_drafts__draft_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spikes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spikes */
        get: operations["list_spikes_api_spikes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spikes/{spike_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Spike */
        get: operations["get_spike_api_spikes__spike_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/spikes/{spike_id}/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Spike Feedbacks */
        get: operations["list_spike_feedbacks_api_spikes__spike_id__feedbacks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/knowledge/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Knowledge Source Health */
        get: operations["list_knowledge_source_health_api_knowledge_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback Volume */
        get: operations["feedback_volume_api_analytics_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Category Mix */
        get: operations["category_mix_api_analytics_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppResponse */
        AppResponse: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Play Package Name */
            play_package_name?: string | null;
            /** Apple Bundle Id */
            apple_bundle_id?: string | null;
        };
        /** CategoriesResponse */
        CategoriesResponse: {
            /** Range Days */
            range_days: number;
            /** Total Classified Feedback */
            total_classified_feedback: number;
            /** Categories */
            categories?: components["schemas"]["CategoryCount"][];
        };
        /** CategoryCount */
        CategoryCount: {
            /** Category */
            category: string;
            /** Sub Category */
            sub_category?: string | null;
            /** Count */
            count: number;
            /** Severity Breakdown */
            severity_breakdown?: {
                [key: string]: number;
            };
            /** Sentiment Breakdown */
            sentiment_breakdown?: {
                [key: string]: number;
            };
        };
        /** CitationSummary */
        CitationSummary: {
            /**
             * Knowledge Chunk Id
             * Format: uuid
             */
            knowledge_chunk_id: string;
            /** Source Url */
            source_url?: string | null;
            /** Source Title */
            source_title: string;
            /** Snippet */
            snippet: string;
        };
        /** ClassificationSummary */
        ClassificationSummary: {
            /** Category */
            category: string;
            /** Sub Category */
            sub_category?: string | null;
            /** Severity */
            severity: string;
            /** Sentiment */
            sentiment: string;
            /** Requires Followup */
            requires_followup: boolean;
            /**
             * Classified At
             * Format: date-time
             */
            classified_at: string;
            /** Language Model Used */
            language_model_used: string;
        };
        /** DraftDetail */
        DraftDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Feedback Id
             * Format: uuid
             */
            feedback_id: string;
            /** App Slug */
            app_slug: string;
            /** Platform */
            platform: string;
            /** Channel */
            channel: string;
            /** Language Code */
            language_code: string;
            /** Status */
            status: string;
            /** Body */
            body: string;
            /** Edited Body */
            edited_body?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Sent At */
            sent_at?: string | null;
            /** Citations */
            citations?: components["schemas"]["CitationSummary"][];
            /** Original Feedback Text */
            original_feedback_text: string;
            /** Original Feedback Author */
            original_feedback_author: string;
            /**
             * Original Feedback Received At
             * Format: date-time
             */
            original_feedback_received_at: string;
            classification?: components["schemas"]["ClassificationSummary"] | null;
        };
        /** DraftListItem */
        DraftListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Feedback Id
             * Format: uuid
             */
            feedback_id: string;
            /** App Slug */
            app_slug: string;
            /** Platform */
            platform: string;
            /** Channel */
            channel: string;
            /** Language Code */
            language_code: string;
            /** Status */
            status: string;
            /**
             * Body Preview
             * @description First 200 characters of the body
             */
            body_preview: string;
            /**
             * Citation Count
             * @default 0
             */
            citation_count: number;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Sent At */
            sent_at?: string | null;
        };
        /** DraftSummary */
        DraftSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Language Code */
            language_code: string;
            /** Body */
            body: string;
            /** Status */
            status: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Sent At */
            sent_at?: string | null;
            /** Citations */
            citations?: components["schemas"]["CitationSummary"][];
        };
        /** FeedbackDetail */
        FeedbackDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** App Slug */
            app_slug: string;
            /** Platform */
            platform: string;
            /** Channel */
            channel: string;
            /** External Id */
            external_id: string;
            /** Author Identifier */
            author_identifier: string;
            /** Raw Text */
            raw_text: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Language Code */
            language_code?: string | null;
            /** App Version */
            app_version?: string | null;
            /** Device Info */
            device_info?: string | null;
            classification?: components["schemas"]["ClassificationSummary"] | null;
            draft?: components["schemas"]["DraftSummary"] | null;
        };
        /** FeedbackSummary */
        FeedbackSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** App Slug */
            app_slug: string;
            /** Platform */
            platform: string;
            /** Channel */
            channel: string;
            /** External Id */
            external_id: string;
            /** Author Identifier */
            author_identifier: string;
            /**
             * Raw Text Preview
             * @description First 200 characters of the body
             */
            raw_text_preview: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Language Code */
            language_code?: string | null;
            /**
             * Has Classification
             * @default false
             */
            has_classification: boolean;
            /**
             * Has Draft
             * @default false
             */
            has_draft: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Name */
            name: string;
            /** Healthy */
            healthy: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description "healthy" or "degraded"
             */
            status: string;
            /**
             * Backend
             * @description "postgres" or "in_memory"
             */
            backend: string;
            /** Checks */
            checks: components["schemas"]["HealthCheck"][];
        };
        /**
         * KnowledgeSourceFreshness
         * @enum {string}
         */
        KnowledgeSourceFreshness: "fresh" | "stale" | "very_stale" | "empty";
        /** KnowledgeSourceHealth */
        KnowledgeSourceHealth: {
            /**
             * Source
             * @description confluence | jira | google_sheets
             */
            source: string;
            /** Document Count */
            document_count: number;
            /** Latest Document At */
            latest_document_at?: string | null;
            freshness: components["schemas"]["KnowledgeSourceFreshness"];
        };
        /** KnowledgeSourcesResponse */
        KnowledgeSourcesResponse: {
            /** Total Documents */
            total_documents: number;
            /** Total Chunks */
            total_chunks: number;
            /** Sources */
            sources?: components["schemas"]["KnowledgeSourceHealth"][];
        };
        /**
         * SpikeDetail
         * @description Same shape as the summary today — kept distinct so future fields
         *     (e.g. linked draft IDs, related spikes) can land on the detail view
         *     only without bloating list payloads.
         */
        SpikeDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Cluster Id
             * Format: uuid
             */
            cluster_id: string;
            /** Cluster Label */
            cluster_label?: string | null;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Count */
            count: number;
            /** Baseline */
            baseline: number;
            /** Ratio */
            ratio: number;
            /** Sample Feedback Ids */
            sample_feedback_ids?: string[];
            /** Alerted At */
            alerted_at?: string | null;
            /**
             * Is Active
             * @description True when the spike window ended within the last 24 hours
             */
            is_active: boolean;
        };
        /** SpikeFeedbacksResponse */
        SpikeFeedbacksResponse: {
            /**
             * Spike Id
             * Format: uuid
             */
            spike_id: string;
            /**
             * Cluster Id
             * Format: uuid
             */
            cluster_id: string;
            /** Feedbacks */
            feedbacks?: components["schemas"]["FeedbackSummary"][];
        };
        /** SpikeSummary */
        SpikeSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Cluster Id
             * Format: uuid
             */
            cluster_id: string;
            /** Cluster Label */
            cluster_label?: string | null;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /** Count */
            count: number;
            /** Baseline */
            baseline: number;
            /** Ratio */
            ratio: number;
            /** Sample Feedback Ids */
            sample_feedback_ids?: string[];
            /** Alerted At */
            alerted_at?: string | null;
            /**
             * Is Active
             * @description True when the spike window ended within the last 24 hours
             */
            is_active: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeBucket */
        VolumeBucket: {
            /**
             * Bucket Date
             * Format: date
             * @description UTC day the count applies to (YYYY-MM-DD)
             */
            bucket_date: string;
            /** Total */
            total: number;
            /** By Channel */
            by_channel?: {
                [key: string]: number;
            };
            /** By Platform */
            by_platform?: {
                [key: string]: number;
            };
            /** By App */
            by_app?: {
                [key: string]: number;
            };
        };
        /** VolumeResponse */
        VolumeResponse: {
            /** Range Days */
            range_days: number;
            /** Buckets */
            buckets?: components["schemas"]["VolumeBucket"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_apps_api_apps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppResponse"][];
                };
            };
        };
    };
    list_feedback_api_feedback_get: {
        parameters: {
            query?: {
                /** @description App slug, e.g. 'toi' */
                app?: string | null;
                /** @description android | ios | unknown */
                platform?: string | null;
                /** @description gmail | google_play | apple_app_store */
                channel?: string | null;
                /** @description ISO-8601 */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feedback_api_feedback__feedback_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedback_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drafts_api_drafts_get: {
        parameters: {
            query?: {
                /** @description App slug, e.g. 'toi' */
                app?: string | null;
                /** @description android | ios | unknown */
                platform?: string | null;
                /** @description gmail | google_play | apple_app_store */
                channel?: string | null;
                /** @description draft | sent | edited | rejected | regenerated */
                status?: string | null;
                /** @description ISO-8601 — only drafts generated after this time */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_draft_api_drafts__draft_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                draft_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spikes_api_spikes_get: {
        parameters: {
            query?: {
                /** @description True → only spikes whose window ended within the last 24h */
                active?: boolean | null;
                /** @description App slug, e.g. 'toi' */
                app?: string | null;
                /** @description ISO-8601. Default: 30 days ago */
                since?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpikeSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spike_api_spikes__spike_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spike_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpikeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_spike_feedbacks_api_spikes__spike_id__feedbacks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spike_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpikeFeedbacksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_knowledge_source_health_api_knowledge_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSourcesResponse"];
                };
            };
        };
    };
    feedback_volume_api_analytics_volume_get: {
        parameters: {
            query?: {
                range_days?: number;
                app?: string | null;
                platform?: string | null;
                channel?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    category_mix_api_analytics_categories_get: {
        parameters: {
            query?: {
                range_days?: number;
                app?: string | null;
                platform?: string | null;
                channel?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
