"""initial_baseline

Revision ID: 0001
Revises: 
Create Date: 2026-05-12 11:11:48.276310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # noqa: F401 — referenced in column types below

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector must exist before any `vector(...)` column is created.
    # Idempotent — safe to re-run.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_actor_occurred_at', 'audit_log', ['actor', 'occurred_at'], unique=False)
    op.create_index('ix_audit_log_occurred_at_desc', 'audit_log', ['occurred_at'], unique=False)
    op.create_table('digest_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('body_html', sa.String(), nullable=False),
    sa.Column('recipients_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_digest_log_type_sent_at', 'digest_log', ['type', 'sent_at'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('app_slug', sa.String(length=32), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('author_identifier', sa.String(length=256), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('normalised_text', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(length=8), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('device_info', sa.String(length=128), nullable=True),
    sa.Column('gmail_thread_id', sa.String(length=128), nullable=True),
    sa.Column('store_review_id', sa.String(length=128), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'app_slug', 'external_id', name='uq_feedback_dedupe')
    )
    op.create_index('ix_feedback_app_platform_received_at', 'feedback', ['app_slug', 'platform', 'received_at'], unique=False)
    op.create_index('ix_feedback_channel_app_received_at', 'feedback', ['channel', 'app_slug', 'received_at'], unique=False)
    op.create_table('feedback_cluster',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('embedding_centroid', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_cluster_centroid_hnsw', 'feedback_cluster', ['embedding_centroid'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_centroid': 'vector_cosine_ops'})
    op.create_table('ingestion_cursor',
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('app_slug', sa.String(length=32), nullable=False),
    sa.Column('cursor_value', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('channel', 'app_slug')
    )
    op.create_table('knowledge_document',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('raw_body', sa.String(), nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_knowledge_document_source')
    )
    op.create_index('ix_knowledge_document_source', 'knowledge_document', ['source'], unique=False)
    op.create_table('classification',
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('requires_followup', sa.Boolean(), nullable=False),
    sa.Column('entities_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language_model_used', sa.String(length=32), nullable=False),
    sa.Column('classified_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('ix_classification_category', 'classification', ['category'], unique=False)
    op.create_index('ix_classification_severity', 'classification', ['severity'], unique=False)
    op.create_table('draft_reply',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=8), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('citations_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('edited_body', sa.String(), nullable=True),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_draft_reply_feedback', 'draft_reply', ['feedback_id'], unique=False)
    op.create_index('ix_draft_reply_status_generated_at', 'draft_reply', ['status', 'generated_at'], unique=False)
    op.create_table('feedback_cluster_membership',
    sa.Column('feedback_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['feedback_cluster.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index('ix_feedback_cluster_membership_cluster', 'feedback_cluster_membership', ['cluster_id'], unique=False)
    op.create_index('ix_feedback_cluster_membership_cluster_received_at', 'feedback_cluster_membership', ['cluster_id', 'received_at'], unique=False)
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('content_tsvector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', content)", persisted=True), nullable=False),
    sa.Column('metadata_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_document_id'], ['knowledge_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_document_id', 'chunk_index', name='uq_knowledge_chunk_position')
    )
    op.create_index('ix_knowledge_chunk_document', 'knowledge_chunk', ['knowledge_document_id'], unique=False)
    op.create_index('ix_knowledge_chunk_embedding_hnsw', 'knowledge_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_knowledge_chunk_tsvector_gin', 'knowledge_chunk', ['content_tsvector'], unique=False, postgresql_using='gin')
    op.create_table('spike_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('window_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('baseline', sa.Float(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.Column('sample_feedback_ids_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('alerted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['feedback_cluster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spike_event_cluster_window_end', 'spike_event', ['cluster_id', 'window_end'], unique=False)
    op.create_index('ix_spike_event_window_end', 'spike_event', ['window_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spike_event_window_end', table_name='spike_event')
    op.drop_index('ix_spike_event_cluster_window_end', table_name='spike_event')
    op.drop_table('spike_event')
    op.drop_index('ix_knowledge_chunk_tsvector_gin', table_name='knowledge_chunk', postgresql_using='gin')
    op.drop_index('ix_knowledge_chunk_embedding_hnsw', table_name='knowledge_chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_knowledge_chunk_document', table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    op.drop_index('ix_feedback_cluster_membership_cluster_received_at', table_name='feedback_cluster_membership')
    op.drop_index('ix_feedback_cluster_membership_cluster', table_name='feedback_cluster_membership')
    op.drop_table('feedback_cluster_membership')
    op.drop_index('ix_draft_reply_status_generated_at', table_name='draft_reply')
    op.drop_index('ix_draft_reply_feedback', table_name='draft_reply')
    op.drop_table('draft_reply')
    op.drop_index('ix_classification_severity', table_name='classification')
    op.drop_index('ix_classification_category', table_name='classification')
    op.drop_table('classification')
    op.drop_index('ix_knowledge_document_source', table_name='knowledge_document')
    op.drop_table('knowledge_document')
    op.drop_table('ingestion_cursor')
    op.drop_index('ix_feedback_cluster_centroid_hnsw', table_name='feedback_cluster', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding_centroid': 'vector_cosine_ops'})
    op.drop_table('feedback_cluster')
    op.drop_index('ix_feedback_channel_app_received_at', table_name='feedback')
    op.drop_index('ix_feedback_app_platform_received_at', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_digest_log_type_sent_at', table_name='digest_log')
    op.drop_table('digest_log')
    op.drop_index('ix_audit_log_occurred_at_desc', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_occurred_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
